"""Generated artifact reconciliation."""

from __future__ import annotations

from typing import Any

from app.release_baseline.models import ArtifactReconciliationItem, count_by
from app.release_baseline.schemas import BASELINE_ONLY_FLAGS


class ArtifactReconciliationEngine:
    """Reconcile generated reports and storage artifacts."""

    def reconcile(self, inventory: dict[str, Any]) -> dict[str, Any]:
        items = [
            self._reconcile(item)
            for item in inventory.get("items", [])
            if str(item.get("file_category", "")).startswith("generated")
            or "archive" in str(item.get("file_category", ""))
            or "diff" in str(item.get("file_category", ""))
        ]
        return {
            "items": items,
            "reconciliation_counts": count_by(items, "reconciliation"),
            **BASELINE_ONLY_FLAGS,
        }

    def _reconcile(self, item: dict[str, Any]) -> dict[str, Any]:
        path = str(item.get("path", ""))
        family = str(item.get("artifact_family", ""))
        if "release_baseline" in path:
            reconciliation = "current phase output"
            reason = "Generated by Phase 65 baseline reconciliation."
        elif family in {"release evidence artifacts", "certification artifacts"}:
            reconciliation = "release evidence"
            reason = "Useful for release baseline evidence."
        elif "research_archive" in path:
            reconciliation = "archive evidence"
            reason = "Archive artifact requires retention policy review."
        elif path.startswith("reports/") or path.startswith("storage/"):
            reconciliation = "validation churn"
            reason = "Likely generated by validation runs."
        else:
            reconciliation = "manual review required"
            reason = "Artifact needs human classification."
        return ArtifactReconciliationItem(
            path=path,
            artifact_type=str(item.get("file_category", "unknown")),
            reconciliation=reconciliation,
            reason=reason,
        ).to_dict()
